---

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/IfUnlessModifier:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Layout/LineLength:
  Max: 80
Naming/MethodParameterName:
  Enabled: false
