#!/usr/bin/env ruby

# frozen_string_literal: true

require 'pathname'

abort 'usage: run <problem>' if ARGV.size != 1

LIBDIR = Pathname.new(__dir__) + 'lib'

problem = ARGV.shift

puts "Solving #{problem}"
require_relative LIBDIR + problem
puts "----> #{Advent.new.solve}"
