#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'lib/support/runner'

unless ARGV.size == 1 && ARGV.first.match(/^[012]\d0[12]$/)
  abort 'usage: run <problem>'
end

puts Runner.new(ARGV.first).solution
